replicaCount: 1

image:
  repository: ""
  tag: "0.1"
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: "inference-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  host: ""        # opcional, si quieres host tipo api.tu-dominio
  path: "/"
  pathType: Prefix

env:
  MLFLOW_TRACKING_URI: "http://mlflow.mlops.svc.cluster.local:5000"
  MODEL_URI: "runs:/ecf399e21bd549c895fb18c2d7eecb9a/model"
  THRESHOLD: "0.5"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

# Para Prometheus Operator (kube-prometheus-stack)
serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
  path: /metrics
