replicaCount: 2

image:
  repository: "614520203750.dkr.ecr.us-east-1.amazonaws.com/tfm-mlops-inference"
  tag: "0.1-manual-3"
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: "inference-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  host: ""
  path: "/"
  pathType: Prefix

env:
  MLFLOW_TRACKING_URI: "http://mlflow.mlops.svc.cluster.local:5000"
  MODEL_URI: "runs:/b2c10be3e0914140be1756a597a2e678/model"
  THRESHOLD: "0.5"

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
  path: /metrics