apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      serviceAccountName: mlflow-sa
      containers:
        - name: mlflow
          image: python:3.11-slim
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: mlflow-config
                  key: AWS_REGION
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: mlflow-config
                  key: AWS_REGION
            - name: MLFLOW_BUCKET
              valueFrom:
                secretKeyRef:
                  name: mlflow-config
                  key: MLFLOW_BUCKET
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-config
                  key: PG_PASSWORD
          command:
            - /bin/sh
            - -c
          args:
            - |
              pip install --no-cache-dir mlflow boto3 psycopg2-binary &&
              mlflow server \
              --host 0.0.0.0 \
              --port 5000 \
              --allowed-hosts "localhost:*,127.0.0.1:*,mlflow.mlops.svc.cluster.local:*" \
              --backend-store-uri "postgresql://mlflow:${PG_PASSWORD}@mlflow-pg-postgresql.mlops.svc.cluster.local:5432/mlflow" \
              --default-artifact-root "s3://${MLFLOW_BUCKET}/"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
