apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-service.fullname" . }}
  labels:
    {{- include "inference-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inference-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: inference
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.env.MLFLOW_TRACKING_URI }}"
            - name: MODEL_URI
              value: "{{ .Values.env.MODEL_URI }}"
            - name: THRESHOLD
              value: "{{ .Values.env.THRESHOLD }}"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
